### PR TITLE
added changes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by diepquynh** [comment]
@RobinRR please edit your 3rd commit message. Check earlier commits for new device supporting commits

**Comment by ghost** [comment]
@remilia15 What do you mean actually?Something to do with the commit message?

**Comment by diepquynh** [comment]
3rd commit seems like adding support for dogo as I see
If you want to do that, make sure the commit message is correctly written, like "Add support for dogo (Xperia ZR)" or sth like that

**Comment by ghost** [comment]
@remilia15  Oh!Yeah,Understood.I should have done this in the first place.Sorry about that.Now it's all done.

**Comment by HassanSardar** [comment]
@RobinRR  Please note that for any org or rom, commit messages are very important. Instead of "Update Hammerhead or xx" it should be clear that what has been done. I'll not merge this one but rather make a new one nd push your changes locally. Thanks.

**Pull request closed without merging**
